### ISSUE TITLE
1.21.1 Fails to launch

### ISSUE THREAD

**Issue by Subnet-Masked** [Norbiros/emojitype#12]
1.21.1 fails to launch despite being listed as compatible. I am using the version for 1.21.1 downloaded from Modrinth.

Error from Fabric Loader:
```
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace 'Minecraft' (minecraft) 1.21.1 with version 1.21.
More details:
	 - Mod 'Emoji Type' (emojitype) 2.2.6-1.21 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

**Comment by Norbiros** [comment]
Fixed in https://github.com/Norbiros/emojitype/commit/62f4b74ed19db473d6f3c8dd980fd054b61e1065. I already created new release `2.2.7`. Thanks for reporting!
